version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  install-dependencies:
    docker:
      - image: cimg/node:18.20
    steps:
      - checkout
      - run: npm ci

  lint:
    docker:
      - image: cimg/node:18.20
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint

  build-and-test:
    docker:
      - image: cimg/node:18.20
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
      - run: npm test

  docker-publish:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t highshow14/flask-mongo-appp:latest .
      - run:
          name: Push to Docker Hub
          command: |
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
            docker push highshow14/flask-mongo-appp:latest

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - build-and-test:
          requires:
            - lint
      - docker-publish:
          requires:
            - build-and-test
